baseURL = 'https://pawsey-internships.github.io/parallel_programming_with_mpi_for_python/'
languageCode = 'en-us'
title = 'Parallel Programming with MPI for Python'
theme = "learn"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
disableBreadcrumb = false
disableNextPrev = false
themeVariant = "green"
disableLandingPageButton = true
